### ISSUE TITLE
Describe the tool mechanisms in the readme

### ISSUE THREAD

**Issue by Karneades** [jblukach/mmi#2]
Hi @jblukach 

Thanks for your tool and your efforts building it! I share some notes after looking at your repo. As I don't use AWS currently, please excuse if my questions are misplaced.

* Why is the LICENSE file green and marked as "known files" in your readme example? Based on what is it flagged as known?
* What is the impact on your tool if atime is disabled due to performance reasons? (_The mmi command line tool lists ... based on user access_)
* Is there only one Linux default installation available or could it differ between customers/installations?
* What is the purpose of the web requests made? Running your tool makes web requests to your own domain and downloads bloom filters. It would help, if you could describe the mechanisms behind `mmi` in the readme so others understand what's going and what the web requests are used for. E.g., which domain for which purpose.
* How often are those bloom filters updated? How could I know what is marked as unknown is really unknown or just a version / image issue between installations?
* It would help, if it would be possible to download the files before running the tool on another machine and use them from disk during offline analysis without making web requests. Would that be something to consider?

Thanks for some feedbacks!

**Comment by jblukach** [comment]
@Karneades

Thank you for taking the time to provide feedback, as I appreciate the input!

`Why is the LICENSE file green and marked as "known files" in your readme example? Based on what is it flagged as known?`

The sha256 hash value of the file contents for LICENSE matches the standard Apache-2.0 license that currently appears 368 times in the data set. Notice that the filename is a lighter gray, as this path does not match where the file is typically found.

`What is the impact on your tool if atime is disabled due to performance reasons? (The mmi command line tool lists ... based on user access)`

Depends on the operating system and file system if the last access time is being recorded or if it is tracking the last status change instead.

https://man7.org/linux/man-pages/man7/inode.7.html

Hashing of the file contents would change that timestamp but not modified. A few other system functions through normal operations can also change that timestamp. I need to add a flag to make hashing optional.

I was referencing the permission level for whether the tool was running as a normal end-user or with root/sudo access. Example, elevated permissions are necessary to hash **/etc/grub2.cfg** or **/etc/grub2-efi.cfg** file contents or returns access denied.

`Is there only one Linux default installation available or could it differ between customers/installations?`

I have only committed to releasing Amazon Linux to ensure sustainability, but I am leaning toward releasing Ubuntu, Windows, and Macintosh.

Only AWS released and verified images are in the data set, with a complete list of covered AMIs provided.

https://static.matchmeta.info/amazonami.json

`What is the purpose of the web requests made? Running your tool makes web requests to your own domain and downloads bloom filters. It would help, if you could describe the mechanisms behind mmi in the readme so others understand what's going and what the web requests are used for. E.g., which domain for which purpose.`

The biggest challenge with this project has always been the distribution. I recently outgrew what I could store in GitHub repositories and Python Packages, so this is a work in progress.

`How often are those bloom filters updated? How could I know what is marked as unknown is really unknown or just a version / image issue between installations?`

The pipeline checks every hour if Amazon has released new AMIs and automatically starts updating the bloom filters. A last update timestamp will be included next time a new image is identified.

`It would help, if it would be possible to download the files before running the tool on another machine and use them from disk during offline analysis without making web requests. Would that be something to consider?`

Yes, I have been trying to keep the collection script at parity with the triage script, but it is likely time to move past that for this and other feature requests. I need to keep it simple but have options for those who need more capabilities.

I hope this helps, and please let me know if you have any more questions.
Looks like I have a few updates that I need to get done 👍

**Comment by Karneades** [comment]
Thanks a lot for your explanations! Much appreciated.
